### ISSUE TITLE
Game crashes on start up

### ISSUE THREAD

**Issue by KateReller** [Szum123321/the_loved_ones#3]
https://crashy.net/u1WHlTmpVZVTlRIfYWGK

**Comment by Szum123321** [comment]
There's far too little information. Please provide the whole log

**Comment by KateReller** [comment]
[crash-2022-07-06_01.49.25-server.txt](https://github.com/Szum123321/the_loved_ones/files/9052303/crash-2022-07-06_01.49.25-server.txt)

**Comment by Szum123321** [comment]
I don't think it's any of my code that's causing the issue. The error appears to occurs due to LibGui package which is a part of qCraft.
